// <auto-generated />
using System;
using DelicateCouriers.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DelicateCouriers.ApiService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726103047_WidenLabelBlobUrl")]
    partial class WidenLabelBlobUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Label", b =>
                {
                    b.Property<int>("LabelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabelID"));

                    b.Property<string>("BlobFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BlobURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ShipmentID")
                        .HasColumnType("integer");

                    b.HasKey("LabelID");

                    b.HasIndex("ShipmentID")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderID"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FulfillmentType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Occasion")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("OrderTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("RequestedCollectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedCollectionTime")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedDeliveryTime")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddressLine1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShippingAddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingMethodId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShippingMethodTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShippingProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingSuburb")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("SpecialTripCustomerLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("SpecialTripCustomerLng")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("SpecialTripDistanceKm")
                        .HasPrecision(10, 1)
                        .HasColumnType("numeric(10,1)");

                    b.Property<decimal?>("SpecialTripQuotedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StoreID")
                        .HasColumnType("integer");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.Property<string>("WooOrderID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WooOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("OrderID");

                    b.HasIndex("StoreID");

                    b.HasIndex("TenantID");

                    b.HasIndex("StoreID", "WooOrderID")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.OrderLineItem", b =>
                {
                    b.Property<int>("OrderLineItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderLineItemID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductSKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TotalWeight")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VariationDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("WeightPerUnit")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int>("WooLineItemID")
                        .HasColumnType("integer");

                    b.Property<int?>("WooProductID")
                        .HasColumnType("integer");

                    b.HasKey("OrderLineItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductSKU");

                    b.HasIndex("WooLineItemID");

                    b.ToTable("OrderLineItems");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PackageMappingRule", b =>
                {
                    b.Property<int>("PackageMappingRuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageMappingRuleID"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PackageTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("PackageMappingRuleID");

                    b.HasIndex("PackageTypeID");

                    b.HasIndex("PackageTypeID", "IsActive");

                    b.ToTable("PackageMappingRules");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PackageType", b =>
                {
                    b.Property<int>("PackageTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageTypeID"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("LengthCm")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StoreID")
                        .HasColumnType("integer");

                    b.Property<int>("WidthCm")
                        .HasColumnType("integer");

                    b.HasKey("PackageTypeID");

                    b.HasIndex("StoreID");

                    b.HasIndex("StoreID", "IsDefault");

                    b.ToTable("PackageTypes");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginAuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("EntityRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("Action", "CreatedOn");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginDebugLog", b =>
                {
                    b.Property<long>("PluginDebugLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PluginDebugLogID"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PluginVersion")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoreID")
                        .HasColumnType("integer");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("PluginDebugLogID");

                    b.ToTable("PluginDebugLogs");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginFeatureFlag", b =>
                {
                    b.Property<int>("FeatureFlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeatureFlagId"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PluginId")
                        .HasColumnType("integer");

                    b.Property<string>("ValueJson")
                        .HasColumnType("text");

                    b.HasKey("FeatureFlagId");

                    b.HasIndex("PluginId", "Key")
                        .IsUnique();

                    b.ToTable("feature_flags", (string)null);
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginInstallation", b =>
                {
                    b.Property<int>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InstallationId"));

                    b.Property<int?>("ApiLatencyMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("InstallKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastHeartbeatOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LicenseId")
                        .HasColumnType("integer");

                    b.Property<string>("PhpVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PluginVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RecentErrorsJson")
                        .HasColumnType("text");

                    b.Property<string>("WcVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WpVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("InstallationId");

                    b.HasIndex("Domain");

                    b.HasIndex("LicenseId", "InstallKey")
                        .IsUnique();

                    b.ToTable("installations", (string)null);
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginLicense", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LicenseId"));

                    b.Property<DateTime?>("ActivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeactivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBeta")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PluginId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("LicenseId");

                    b.HasIndex("LicenseKey")
                        .IsUnique();

                    b.HasIndex("PluginId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.ToTable("licenses", (string)null);
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginProduct", b =>
                {
                    b.Property<int>("PluginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PluginId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PluginId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("plugins", (string)null);
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginRelease", b =>
                {
                    b.Property<int>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReleaseId"));

                    b.Property<string>("Changelog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("MinPhpVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MinWcVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MinWpVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("PackageData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("PluginId")
                        .HasColumnType("integer");

                    b.Property<string>("RolloutStage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WithdrawnBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("WithdrawnOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReleaseId");

                    b.HasIndex("PluginId", "Status");

                    b.HasIndex("PluginId", "Version")
                        .IsUnique();

                    b.ToTable("plugin_releases", (string)null);
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginRolloutRule", b =>
                {
                    b.Property<int>("RolloutRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolloutRuleId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("RolloutRuleId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("rollout_rules", (string)null);
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginTelemetryEvent", b =>
                {
                    b.Property<long>("TelemetryEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelemetryEventId"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("InstallationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<int?>("PluginId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TelemetryEventId");

                    b.HasIndex("InstallationId");

                    b.HasIndex("EventType", "OccurredOn");

                    b.ToTable("telemetry_events", (string)null);
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("ShipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShipmentID"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsignmentID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CourierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CourierService")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<string>("ShipmentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TrackingPushedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ShipmentID");

                    b.HasIndex("ConsignmentID")
                        .IsUnique();

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("TrackingNumber");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreID"));

                    b.Property<string>("BookingTriggerStatuses")
                        .HasColumnType("text");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CollectionAddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("CollectionAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("CollectionCity")
                        .HasColumnType("text");

                    b.Property<string>("CollectionCompanyName")
                        .HasColumnType("text");

                    b.Property<string>("CollectionContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("CollectionContactName")
                        .HasColumnType("text");

                    b.Property<string>("CollectionContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("CollectionCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("CollectionLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CollectionLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("CollectionPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("CollectionProvince")
                        .HasColumnType("text");

                    b.Property<string>("CollectionSuburb")
                        .HasColumnType("text");

                    b.Property<string>("CollectionTimeFrom")
                        .HasColumnType("text");

                    b.Property<string>("CollectionTimeTo")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultServiceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryTimeFrom")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryTimeTo")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShiplogicAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("ShiplogicProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("ShopifyAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("ShopifyStoreUrl")
                        .HasColumnType("text");

                    b.Property<string>("ShopifyWebhookSecret")
                        .HasColumnType("text");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.Property<string>("WebhookSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WooCommerceURL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("WooConsumerKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WooConsumerSecret")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("StoreID");

                    b.HasIndex("TenantID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.SystemEvent", b =>
                {
                    b.Property<long>("SystemEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SystemEventID"));

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorLabel")
                        .HasColumnType("text");

                    b.Property<int?>("ActorUserID")
                        .HasColumnType("integer");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("EntityRef")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int?>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("SystemEventID");

                    b.ToTable("SystemEvents");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantID"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ShiplogicBearerToken")
                        .HasColumnType("text");

                    b.Property<string>("TenantAPIKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TenantID");

                    b.HasIndex("TenantAPIKey")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.TrackingEvent", b =>
                {
                    b.Property<int>("TrackingEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackingEventID"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExternalEventId")
                        .HasColumnType("text");

                    b.Property<int>("ShipmentID")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("TrackingEventID");

                    b.HasIndex("EventTimestamp");

                    b.HasIndex("ShipmentID");

                    b.ToTable("TrackingEvents");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SupabaseUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("TenantID")
                        .HasColumnType("integer");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.HasIndex("TenantID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Label", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.Shipment", "Shipment")
                        .WithOne("Label")
                        .HasForeignKey("DelicateCouriers.Domain.Entities.Label", "ShipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Order", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelicateCouriers.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.OrderLineItem", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.Order", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PackageMappingRule", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.PackageType", "PackageType")
                        .WithMany("MappingRules")
                        .HasForeignKey("PackageTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageType");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PackageType", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.Store", "Store")
                        .WithMany("PackageTypes")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginFeatureFlag", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.PluginProduct", "Plugin")
                        .WithMany("FeatureFlags")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginInstallation", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.PluginLicense", "License")
                        .WithMany("Installations")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginLicense", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.PluginProduct", "Plugin")
                        .WithMany("Licenses")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginRelease", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.PluginProduct", "Plugin")
                        .WithMany("Releases")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginRolloutRule", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.PluginRelease", "Release")
                        .WithMany("RolloutRules")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("DelicateCouriers.Domain.Entities.Shipment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Store", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Stores")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.TrackingEvent", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.Shipment", "Shipment")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("ShipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.User", b =>
                {
                    b.HasOne("DelicateCouriers.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Order", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PackageType", b =>
                {
                    b.Navigation("MappingRules");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginLicense", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginProduct", b =>
                {
                    b.Navigation("FeatureFlags");

                    b.Navigation("Licenses");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.PluginRelease", b =>
                {
                    b.Navigation("RolloutRules");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Label");

                    b.Navigation("TrackingEvents");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Store", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PackageTypes");
                });

            modelBuilder.Entity("DelicateCouriers.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Stores");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
