using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using DelicateCouriers.ApiService.Data;

#nullable disable

namespace DelicateCouriers.ApiService.Migrations;

/// <summary>
/// Plugin Platform module: the API becomes the distribution + licensing
/// backend for the WordPress/WooCommerce plugins. Creates 8 tables
/// (snake_case per the module spec): plugins, plugin_releases, licenses,
/// installations, telemetry_events, feature_flags, rollout_rules,
/// audit_logs. Release ZIP bytes are stored in-DB (bytea) behind the
/// IPluginPackageStorage abstraction — no external object storage needed.
/// Seeds the default plugin product row ("delicate-courier-platform").
/// Hand-written raw SQL with IF NOT EXISTS so it is idempotent against
/// the shared dev/prod database.
/// </summary>
[DbContext(typeof(AppDbContext))]
[Migration("20260725190000_AddPluginPlatform")]
public partial class AddPluginPlatform : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "plugins" (
                "PluginId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Slug" character varying(100) NOT NULL,
                "Name" character varying(200) NOT NULL,
                "Description" character varying(1000) NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                "CreatedOn" timestamp with time zone NOT NULL,
                "CreatedBy" character varying(100) NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_plugins_Slug" ON "plugins" ("Slug");

            CREATE TABLE IF NOT EXISTS "plugin_releases" (
                "ReleaseId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PluginId" integer NOT NULL REFERENCES "plugins" ("PluginId") ON DELETE CASCADE,
                "Version" character varying(50) NOT NULL,
                "Changelog" text NOT NULL,
                "MinWpVersion" character varying(20) NULL,
                "MinWcVersion" character varying(20) NULL,
                "MinPhpVersion" character varying(20) NULL,
                "Sha256" character varying(64) NOT NULL,
                "StorageKey" character varying(200) NOT NULL,
                "PackageData" bytea NOT NULL,
                "FileSizeBytes" bigint NOT NULL,
                "FileName" character varying(300) NOT NULL,
                "RolloutStage" character varying(20) NOT NULL,
                "Status" character varying(20) NOT NULL,
                "CreatedOn" timestamp with time zone NOT NULL,
                "CreatedBy" character varying(100) NOT NULL,
                "WithdrawnOn" timestamp with time zone NULL,
                "WithdrawnBy" character varying(100) NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_plugin_releases_PluginId_Version" ON "plugin_releases" ("PluginId", "Version");
            CREATE INDEX IF NOT EXISTS "IX_plugin_releases_PluginId_Status" ON "plugin_releases" ("PluginId", "Status");

            CREATE TABLE IF NOT EXISTS "licenses" (
                "LicenseId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PluginId" integer NOT NULL REFERENCES "plugins" ("PluginId") ON DELETE CASCADE,
                "LicenseKey" character varying(64) NOT NULL,
                "TenantId" integer NULL,
                "StoreId" integer NULL,
                "Domain" character varying(255) NULL,
                "Status" character varying(20) NOT NULL,
                "IsInternal" boolean NOT NULL DEFAULT FALSE,
                "IsBeta" boolean NOT NULL DEFAULT FALSE,
                "ActivatedOn" timestamp with time zone NULL,
                "DeactivatedOn" timestamp with time zone NULL,
                "ExpiresOn" timestamp with time zone NULL,
                "CreatedOn" timestamp with time zone NOT NULL,
                "CreatedBy" character varying(100) NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_licenses_LicenseKey" ON "licenses" ("LicenseKey");
            CREATE INDEX IF NOT EXISTS "IX_licenses_StoreId" ON "licenses" ("StoreId");
            CREATE INDEX IF NOT EXISTS "IX_licenses_TenantId" ON "licenses" ("TenantId");

            CREATE TABLE IF NOT EXISTS "installations" (
                "InstallationId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "LicenseId" integer NOT NULL REFERENCES "licenses" ("LicenseId") ON DELETE CASCADE,
                "InstallKey" character varying(64) NOT NULL,
                "Domain" character varying(255) NOT NULL,
                "PluginVersion" character varying(50) NULL,
                "WpVersion" character varying(20) NULL,
                "WcVersion" character varying(20) NULL,
                "PhpVersion" character varying(20) NULL,
                "LastHeartbeatOn" timestamp with time zone NULL,
                "ApiLatencyMs" integer NULL,
                "RecentErrorsJson" text NULL,
                "CreatedOn" timestamp with time zone NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_installations_LicenseId_InstallKey" ON "installations" ("LicenseId", "InstallKey");
            CREATE INDEX IF NOT EXISTS "IX_installations_Domain" ON "installations" ("Domain");

            CREATE TABLE IF NOT EXISTS "telemetry_events" (
                "TelemetryEventId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "InstallationId" integer NULL,
                "PluginId" integer NULL,
                "EventType" character varying(100) NOT NULL,
                "PayloadJson" text NULL,
                "OccurredOn" timestamp with time zone NOT NULL,
                "ReceivedOn" timestamp with time zone NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_telemetry_events_InstallationId" ON "telemetry_events" ("InstallationId");
            CREATE INDEX IF NOT EXISTS "IX_telemetry_events_EventType_OccurredOn" ON "telemetry_events" ("EventType", "OccurredOn");

            CREATE TABLE IF NOT EXISTS "feature_flags" (
                "FeatureFlagId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PluginId" integer NOT NULL REFERENCES "plugins" ("PluginId") ON DELETE CASCADE,
                "Key" character varying(100) NOT NULL,
                "Enabled" boolean NOT NULL DEFAULT FALSE,
                "ValueJson" text NULL,
                "CreatedOn" timestamp with time zone NOT NULL,
                "ChangedOn" timestamp with time zone NULL,
                "ChangedBy" character varying(100) NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_feature_flags_PluginId_Key" ON "feature_flags" ("PluginId", "Key");

            CREATE TABLE IF NOT EXISTS "rollout_rules" (
                "RolloutRuleId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ReleaseId" integer NOT NULL REFERENCES "plugin_releases" ("ReleaseId") ON DELETE CASCADE,
                "RuleType" character varying(30) NOT NULL,
                "Value" character varying(255) NOT NULL,
                "CreatedOn" timestamp with time zone NOT NULL,
                "CreatedBy" character varying(100) NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_rollout_rules_ReleaseId" ON "rollout_rules" ("ReleaseId");

            CREATE TABLE IF NOT EXISTS "audit_logs" (
                "AuditLogId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Action" character varying(100) NOT NULL,
                "Actor" character varying(255) NOT NULL,
                "EntityType" character varying(50) NULL,
                "EntityRef" character varying(255) NULL,
                "DetailsJson" text NULL,
                "IpAddress" character varying(45) NULL,
                "CreatedOn" timestamp with time zone NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_audit_logs_Action_CreatedOn" ON "audit_logs" ("Action", "CreatedOn");
            """);

        migrationBuilder.Sql("""
            INSERT INTO "plugins" ("Slug", "Name", "Description", "IsActive", "CreatedOn", "CreatedBy")
            SELECT 'delicate-courier-platform', 'Delicate Courier Platform', 'Default WooCommerce plugin (live rates + signed order push).', TRUE, NOW(), 'migration'
            WHERE NOT EXISTS (SELECT 1 FROM "plugins" WHERE "Slug" = 'delicate-courier-platform');
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS "rollout_rules";
            DROP TABLE IF EXISTS "feature_flags";
            DROP TABLE IF EXISTS "telemetry_events";
            DROP TABLE IF EXISTS "installations";
            DROP TABLE IF EXISTS "licenses";
            DROP TABLE IF EXISTS "plugin_releases";
            DROP TABLE IF EXISTS "plugins";
            DROP TABLE IF EXISTS "audit_logs";
            """);
    }
}
